# Generated by Django 3.1.4 on 2020-12-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20201214_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='id',
        ),
    ]
